# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [main]

jobs:
  - name: Git configuration
    run: |
      git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      git config --global user.name "GitHub Actions"

  # Bump package version
  # Use tag latest
  - name: Bump release version
    run: |
      echo "NEW_VERSION=$(npm --no-git-tag-version version $RELEASE_TYPE)" >> $GITHUB_ENV
      echo "RELEASE_TAG=latest" >> $GITHUB_ENV
    env:
      RELEASE_TYPE: minor

  - name: Commit package.json changes and create tag
  run: |
    git add "package.json"
    git commit -m "chore: release ${{ env.NEW_VERSION }}"
    git tag ${{ env.NEW_VERSION }}


  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      # - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
